import { Injectable, ServiceUnavailableException } from '@nestjs/common';
import { SettingsService } from '../../settings/settings.service';

interface GitHubRefResponse {
  object?: {
    sha?: string;
  };
}

interface GitHubPullRequestResponse {
  number?: number;
  html_url?: string;
}

@Injectable()
export class GitHubClientService {
  constructor(private readonly settingsService: SettingsService) {}

  async getConnectionStatus() {
    const githubSettings = await this.settingsService.getGitHubSettings();
    return {
      configured: githubSettings.configured,
      owner: githubSettings.owner,
      defaultRepository: githubSettings.defaultRepository,
      prCreationEnabled: githubSettings.prCreationEnabled,
    };
  }

  async createPullRequest(params: {
    title: string;
    body: string;
    repository?: string;
    baseBranch?: string;
    draft?: boolean;
  }) {
    const executionMode = await this.settingsService.getActionExecutionMode();

    if (executionMode === 'mock') {
      const timestamp = Date.now();
      const repository = params.repository ?? 'mock-repository';
      const branch = `work-os/mock-pr-${timestamp}`;
      return {
        mode: 'mock' as const,
        repository,
        branch,
        pullRequestNumber: Math.floor(timestamp / 1000),
        pullRequestUrl: `https://github.com/mock-org/${repository}/pull/${Math.floor(timestamp / 1000)}`,
      };
    }

    const githubSettings = await this.settingsService.getGitHubSettings();

    if (
      !githubSettings.token ||
      !githubSettings.owner ||
      !githubSettings.defaultRepository
    ) {
      throw new ServiceUnavailableException(
        'GitHub settings are not fully configured for PR creation',
      );
    }

    if (!githubSettings.prCreationEnabled) {
      throw new ServiceUnavailableException('GitHub PR creation is disabled');
    }

    const owner = githubSettings.owner;
    const repository = params.repository ?? githubSettings.defaultRepository;
    const baseBranch =
      params.baseBranch ?? githubSettings.defaultBaseBranch ?? 'main';
    const draft = params.draft ?? githubSettings.defaultDraftPr;

    const baseRef = await this.githubRequest<GitHubRefResponse>({
      token: githubSettings.token,
      path: `/repos/${owner}/${repository}/git/ref/heads/${encodeURIComponent(baseBranch)}`,
      method: 'GET',
    });

    const baseSha = baseRef.object?.sha;
    if (!baseSha) {
      throw new ServiceUnavailableException(
        'GitHub base branch ref did not include a commit SHA',
      );
    }

    const branchSlug = this.slugify(params.title).slice(0, 40) || 'task';
    const branch = `work-os/${branchSlug}-${Date.now().toString().slice(-6)}`;

    await this.githubRequest({
      token: githubSettings.token,
      path: `/repos/${owner}/${repository}/git/refs`,
      method: 'POST',
      body: {
        ref: `refs/heads/${branch}`,
        sha: baseSha,
      },
    });

    const scaffoldPath = `.work-os/pr-scaffolds/${new Date().toISOString().replaceAll(':', '-')}-${branchSlug}.md`;
    const encodedScaffoldPath = scaffoldPath
      .split('/')
      .map((segment) => encodeURIComponent(segment))
      .join('/');
    const scaffoldContent = [
      `# ${params.title}`,
      '',
      params.body,
      '',
      'Generated by Work OS automated PR workflow.',
    ].join('\n');

    await this.githubRequest({
      token: githubSettings.token,
      path: `/repos/${owner}/${repository}/contents/${encodedScaffoldPath}`,
      method: 'PUT',
      body: {
        message: `chore(work-os): scaffold ${params.title}`,
        content: Buffer.from(scaffoldContent, 'utf8').toString('base64'),
        branch,
      },
    });

    const pullRequest = await this.githubRequest<GitHubPullRequestResponse>({
      token: githubSettings.token,
      path: `/repos/${owner}/${repository}/pulls`,
      method: 'POST',
      body: {
        title: params.title,
        body: params.body,
        head: branch,
        base: baseBranch,
        draft,
      },
    });

    if (!pullRequest.number || !pullRequest.html_url) {
      throw new ServiceUnavailableException(
        'GitHub pull request response was missing expected fields',
      );
    }

    return {
      mode: 'live' as const,
      repository,
      branch,
      pullRequestNumber: pullRequest.number,
      pullRequestUrl: pullRequest.html_url,
      draft,
    };
  }

  private async githubRequest<T = Record<string, unknown>>(params: {
    token: string;
    path: string;
    method: 'GET' | 'POST' | 'PUT';
    body?: Record<string, unknown>;
  }): Promise<T> {
    const response = await fetch(`https://api.github.com${params.path}`, {
      method: params.method,
      headers: {
        Authorization: 'Bearer ' + params.token,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      ...(params.body ? { body: JSON.stringify(params.body) } : {}),
    });

    if (!response.ok) {
      throw new ServiceUnavailableException(
        `GitHub API request failed: ${response.status} ${response.statusText}`,
      );
    }

    return (await response.json()) as T;
  }

  private slugify(value: string) {
    return value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }
}
